<?php
session_start(); require '../database/config.php'; require '../includes/auth.php'; requireAdmin();
$pdo=getConnection(); $message=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 $name=trim($_POST['name']??''); $location=trim($_POST['location']??''); $address=trim($_POST['address']??''); $description=trim($_POST['description']??'');
 if($name!=='' && $location!==''){ $s=$pdo->prepare('INSERT INTO dormitories(name,location,address,description) VALUES(:name,:location,:address,:description)'); $s->execute(['name'=>$name,'location'=>$location,'address'=>$address?:null,'description'=>$description?:null]); $message='Dormitory added.'; }
}
$rows=$pdo->query('SELECT * FROM dormitories ORDER BY location')->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dormitories | Admin</title><link rel="stylesheet" href="../assets/css/admin.css"></head><body><header class="admin-header"><a href="../index.php" class="brand-link"><img src="../assets/images/logo-dark.svg" alt="Obeda Dormitories"></a><div><span>Administrator</span><a class="logout" href="../logout.php">Logout</a></div></header><div class="admin-layout"><aside><div class="side-title">ADMIN</div><nav><a href="dashboard.php">Dashboard</a><a href="viewing_requests.php">Viewing Requests</a><a href="room_applications.php">Room Applications</a><a href="rooms.php">Rooms</a><a class="active" href="dormitories.php">Dormitories</a><a href="users.php">Users</a></nav></aside><main class="admin-main"><h1>Dormitories</h1><?php if($message): ?><div class="alert success"><?=h($message)?></div><?php endif; ?><div class="two-col"><section class="panel"><h2>Add Dormitory</h2><form method="post"><label>Name</label><input name="name" required><label>Location</label><input name="location" required><label>Address</label><input name="address"><label>Description</label><textarea name="description"></textarea><button class="primary">Add Dormitory</button></form></section><section class="panel"><h2>Existing Locations</h2><?php foreach($rows as $r): ?><div class="list-row"><strong><?=h($r['name'])?></strong><span><?=h($r['location'])?></span></div><?php endforeach; ?></section></div></main></div></body></html>
