<?php
session_start(); require '../database/config.php'; require '../includes/auth.php'; requireAdmin();
$pdo=getConnection(); $message=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 $d=(int)($_POST['dormitory_id']??0); $num=trim($_POST['room_number']??''); $type=$_POST['room_type']??'4_person'; $cap=max(1,(int)($_POST['capacity']??4)); $rate=max(0,(float)($_POST['monthly_rate']??0)); $slots=max(0,min($cap,(int)($_POST['available_slots']??0)));
 if($d && $num!=='' && in_array($type,['4_person','female_exclusive','other'],true)) { $s=$pdo->prepare("INSERT INTO rooms(dormitory_id,room_number,room_type,capacity,monthly_rate,available_slots,status) VALUES(:d,:n,:t,:c,:r,:s,IF(:s2>0,'available','full'))"); $s->execute(['d'=>$d,'n'=>$num,'t'=>$type,'c'=>$cap,'r'=>$rate,'s'=>$slots,'s2'=>$slots]); $message='Room added.'; }
}
$dorms=$pdo->query("SELECT id,name,location FROM dormitories WHERE status='active' ORDER BY location")->fetchAll(); $rows=$pdo->query("SELECT r.*,d.location FROM rooms r JOIN dormitories d ON d.id=r.dormitory_id ORDER BY d.location,r.room_number")->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rooms | Admin</title><link rel="stylesheet" href="../assets/css/admin.css"></head><body><header class="admin-header"><a href="../index.php" class="brand-link"><img src="../assets/images/logo-dark.svg" alt="Obeda Dormitories"></a><div><span>Administrator</span><a class="logout" href="../logout.php">Logout</a></div></header><div class="admin-layout"><aside><div class="side-title">ADMIN</div><nav><a href="dashboard.php">Dashboard</a><a href="viewing_requests.php">Viewing Requests</a><a href="room_applications.php">Room Applications</a><a class="active" href="rooms.php">Rooms</a><a href="dormitories.php">Dormitories</a><a href="users.php">Users</a></nav></aside><main class="admin-main"><h1>Rooms</h1><?php if($message): ?><div class="alert success"><?=h($message)?></div><?php endif; ?><div class="two-col"><section class="panel"><h2>Add Room</h2><form method="post"><label>Dormitory</label><select name="dormitory_id" required><?php foreach($dorms as $d): ?><option value="<?=h((string)$d['id'])?>"><?=h($d['location'])?></option><?php endforeach; ?></select><label>Room Number</label><input name="room_number" required><label>Type</label><select name="room_type"><option value="4_person">4 person</option><option value="female_exclusive">Female exclusive</option><option value="other">Other</option></select><label>Capacity</label><input type="number" name="capacity" min="1" value="4"><label>Monthly Rate</label><input type="number" step="0.01" name="monthly_rate" min="0" value="0"><label>Available Slots</label><input type="number" name="available_slots" min="0" value="4"><button class="primary">Add Room</button></form></section><section class="panel table-wrap"><h2>Existing Rooms</h2><table><thead><tr><th>Location</th><th>Room</th><th>Type</th><th>Slots</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?=h($r['location'])?></td><td><?=h($r['room_number'])?></td><td><?=h($r['room_type'])?></td><td><?=h((string)$r['available_slots'])?> / <?=h((string)$r['capacity'])?></td><td><span class="status <?=h($r['status'])?>"><?=h(ucfirst($r['status']))?></span></td></tr><?php endforeach; if(!$rows): ?><tr><td colspan="5">No rooms have been added yet.</td></tr><?php endif; ?></tbody></table></section></div></main></div></body></html>
